FROM node:20-alpine
RUN corepack enable

WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/server ./packages/server
COPY packages/shared ./packages/shared

WORKDIR /app/packages/server
