FROM node:20-alpine
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/client/package.json ./packages/client/
COPY packages/shared ./packages/shared

RUN pnpm install

WORKDIR /app/packages/client

EXPOSE 5173 9222
